on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

name: Scala Steward

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Scala Steward GitHub Action
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.READ_WRITE_PACKAGES }} # Scala Steward needs it to open PRs
          author-name: Scala Steward
          author-email: 2750485+joriscode@users.noreply.github.com
          branches: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || 'master' }}
    env:
      GITHUB_TOKEN: ${{ secrets.READ_WRITE_PACKAGES }} # Sbt reads it to resolve Github packages
